/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>

#include "platform.h"
#include "logger.h"
#include <string.h>
/*

1118
*/
int main(void)
{
    char buffor[] ="Hello THis is my test\n\r";
    P_init_platform();
    logger_init();
    logger_write(buffor,strlen(buffor));
    logger_printf("Temperatura:%.2f;Himitiy%.2f",23.24,85.12);
    logger_status_t log;
    logger_deinit();
    log =logger_write(buffor,strlen(buffor));
}
