/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <sys/types.h>
#include "Third_party/FatFs/source/ff.h"
#include "platform.h"

FATFS fs[1];
FRESULT res ;
FIL fil;
PARTITION VolToPart[FF_VOLUMES] = {
    {0, 0},   // "0:" → physical drive 0, whole drive
    {1, 0},   // "1:" → physical drive 1, whole drive
};
/*

1118
*/
int main(void)
{

    P_init_platform();
    uint d;
    
    res = f_mount(&fs[0], "1:", 1);
    res =f_open(&fil, "1:Text.txt", FA_WRITE | FA_OPEN_APPEND);
    res = f_write(&fil, "Test Test", 11, &d);
    /* Append a line */
    f_close(&fil);

    int a;
}
